fail_fast: true
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 24.3.0
  hooks:
  - id: black
    language_version: python3.11
- repo: https://github.com/PyCQA/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
- repo: local
  hooks:
  - id: mypy
    name: mypy
    entry: mypy
    language: python
    language_version: python3.11
    additional_dependencies:
    - mypy>=1.9.0, <2.0.0
    types:
    - python
    require_serial: true
    verbose: true
  - id: pytest
    name: pytest
    entry: .venv-check/bin/pytest
    language: script
    types:
    - python
    pass_filenames: false
    args:
    - -v
    - -m
    - not slow
