fail_fast: true
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
- repo: local
  hooks:
  - id: mypy
    name: mypy
    entry: mypy
    language: python
    language_version: python3.11
    additional_dependencies:
    - mypy>=1.9.0, <2.0.0
    types:
    - python
    require_serial: true
    verbose: true
