[tool.mypy]
python_version = "3.11"
python_executable = ".venv-check/bin/python"
strict = true
files = "*.py"
mypy_path = "."

[tool.pytest.ini_options]
pythonpath = "test"
testpaths = "test"
norecursedirs = "test/disable"
addopts = "--random-order"
log_cli_level = "WARNING"
markers = [
    "unit",
    "func",
    "perf",
    "slow",
]
